# Numpy Practice - Solutions - Unibs 2021

#### Import the numpy package under the name `np` and print version and configuration (base)
`hint: import … as, np.__version__, np.show_config`

In [44]:
import numpy as np

print(np.__version__)
np.show_config()

1.19.2
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Admin/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Admin/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Admin/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Admin/Anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Admin/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Admin/Anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Admin/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Admin/Anaconda3\\Library\\include']


## Base Practice

#### 1. Create a null vector of size 10 but the fifth value which is 1 (base)
`hint: array[4]`

In [6]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 2. Create a 3x3 matrix with values ranging from 0 to 8 with zeros on the diagonal (base)
`hint: np.arange, reshape, np.eye`

In [65]:
Z = np.arange(9).reshape(3, 3)
K = np.eye(3, dtype=int)
Z = Z - Z * K
print(Z)

[[0 1 2]
 [3 0 5]
 [6 7 0]]


#### 3. How to add a border (filled with 0's) around an 5x5 matrix of ones? (base)
`hint: np.ones, np.pad`

In [63]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

# # Using fancy indexing
# Z[:, [0, -1]] = 0
# Z[[0, -1], :] = 0
# print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 4. Normalize a 5x5 random matrix (base)
`hint: (x - mean) / std`

In [64]:
Z = np.random.random((5,5))
Z = (Z - np.mean(Z)) / (np.std (Z))
print(Z)

[[-0.96971602  0.85202833 -0.49253695  0.89088922  1.51394809]
 [-1.06676912 -0.91463076 -1.33607957  0.85718625  1.43509601]
 [-0.58426717  0.04199447 -1.20234119 -1.63415771  0.09986147]
 [ 1.17860983  1.26644423 -1.00996969  0.0207842   0.75429635]
 [-1.13482959  0.84041494  0.55444368  1.04373754 -1.00443684]]


#### 5. Multiply a 5x3 matrix of ones by a 3x2 matrix of ones (real matrix product) (base)
`hint:`

In [66]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

# # Alternative solution, in Python 3.5 and above
# Z = np.ones((5,3)) @ np.ones((3,2))
# print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


## Intermediate Practice

#### 6. Create a vector of size 10 with values ranging from 0 to 1, both excluded (intermediate)
`hint: np.linspace`

In [39]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 7. Create a random vector of size 10 with values in range (-3, 12) and sort it (intermediate)
`hint: sort`

In [106]:
Z = np.random.random(10) * 15 - 3
Z.sort()
print(Z)

[-2.76389001 -2.31901056 -2.12172018 -2.04065297 -1.77283243  3.22737092
  4.28000684  7.08956454  7.95813965  8.63528951]


#### 8. Create random vector of size 10 and replace the maximum value by its additive inverse and the minimum value (of the original array) with the median value (intermediate)
`hint: argmax, argmin`

In [113]:
Z = np.random.random(10)
Z[Z.argmin()] = np.median(Z)
Z[Z.argmax()] = -Z.max()
print(Z)

[ 0.85134797  0.67615506  0.77661793  0.64396933  0.6117836   0.4401557
 -0.92628723  0.4599881   0.48866865  0.84264559]


#### 9. How to randomly place p elements in a 2D matrix? (intermediate)
`hint: np.put, np.random.choice`

In [114]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 10. Subtract the mean of each row of a random 5x10 matrix (intermediate)
`hint: mean(axis=,keepdims=)`

In [116]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

[[-0.24379303  0.10173166  0.21508807 -0.21256323  0.29380342 -0.2599254
   0.08407095  0.12658622 -0.32496347  0.21996481]
 [-0.21224057 -0.25192182 -0.28956618 -0.27774593 -0.10536859  0.22115939
   0.26244561  0.39699984  0.03392306  0.22231519]
 [-0.32098102 -0.13073184 -0.28951608  0.04046951 -0.09665224  0.41068355
  -0.24575313  0.22835714 -0.07434736  0.47847148]
 [-0.16861593 -0.45975483  0.09651831  0.07545285 -0.00914285  0.20283116
  -0.42315504  0.3395927   0.07627817  0.26999546]
 [ 0.33838531 -0.20214632 -0.22161304  0.43902186  0.2627361   0.10732619
   0.18110014 -0.55320907 -0.53142104  0.17981988]]
